spring.application.name=demo
server.port=8080

spring.datasource.url=jdbc:h2:mem:tododb
#jdbc-java database connectivity, h2:h2 database engine we use, mem:in memory database, tododb-name of the database
#The JDBC URL provides the connection
#information that tells the application what database to use and where/how to reach it.
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=Vikash
spring.datasource.password=Naveen

spring.h2.console.enabled=true

#What is H2 Console?
#It's a small web UI that lets you interact with your H2 database through a browser.
#Without it:
#Spring Boot
#    ↓
#H2 Database

#With it:
#                    ┌──────────────┐
#                    │   Browser    │
#                    │  H2 Console  │
#                    └──────┬───────┘
#                           ↓
#Spring Boot ───────────→ H2 Database

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update